-- Type coverage fixture (SPEC §17). Recreated from scratch on every prepare.sh run.
DROP TABLE IF EXISTS smoke;
CREATE TABLE smoke (
    id   integer PRIMARY KEY,
    name text NOT NULL
);
INSERT INTO smoke (id, name) VALUES (1, 'hello'), (2, 'wörld'), (3, '日本語');

DROP TYPE IF EXISTS mood CASCADE;
CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');

DROP TABLE IF EXISTS all_types;
CREATE TABLE all_types (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    c_bool          boolean,
    c_int2          smallint,
    c_int4          integer,
    c_int8          bigint,
    c_float4        real,
    c_float8        double precision,
    c_numeric       numeric(65, 30),
    c_text          text,
    c_varchar       varchar(255),
    c_char          char(8),
    c_name          name,
    c_bytea         bytea,
    c_date          date,
    c_time          time,
    c_timetz        timetz,
    c_timestamp     timestamp,
    c_timestamptz   timestamptz,
    c_uuid          uuid,
    c_json          json,
    c_jsonb         jsonb,
    c_int_array     integer[],
    c_text_array    text[],
    c_mood          mood,
    c_interval      interval,
    c_inet          inet,
    c_bit           bit(8),
    c_generated     bigint GENERATED ALWAYS AS (c_int4::bigint * 2) STORED
);
COMMENT ON TABLE all_types IS 'Every mapped PostgreSQL type, plus NULLs and extremes';
COMMENT ON COLUMN all_types.c_numeric IS 'Exact decimal, never a Double';

-- Row 1: ordinary values.
INSERT INTO all_types (
    c_bool, c_int2, c_int4, c_int8, c_float4, c_float8, c_numeric,
    c_text, c_varchar, c_char, c_name, c_bytea,
    c_date, c_time, c_timetz, c_timestamp, c_timestamptz,
    c_uuid, c_json, c_jsonb, c_int_array, c_text_array, c_mood,
    c_interval, c_inet, c_bit
) VALUES (
    true, 32767, 2147483647, 9223372036854775807, 1.5, 2.5,
    '12345678901234567890123456789012345.123456789012345678901234567890',
    'ascii text', 'varchar', 'char8   ', 'a_name', '\x000102ff'::bytea,
    '2024-03-10', '02:30:00.123456', '02:30:00+07', '2024-03-10 02:30:00.123456',
    '2024-03-10 02:30:00.123456+00',
    '11111111-2222-3333-4444-555555555555', '{"a":1}', '{"b":[1,2,3]}',
    ARRAY[1, NULL, 3], ARRAY['a', NULL, 'ç'], 'happy',
    '1 year 2 mons 3 days 04:05:06.5', '192.168.1.10/24', B'10110001'
);

-- Row 2: NULL in every nullable column.
INSERT INTO all_types (c_bool) VALUES (NULL);

-- Row 3: extremes and Unicode.
INSERT INTO all_types (
    c_int2, c_int4, c_int8, c_float4, c_float8, c_numeric,
    c_text, c_bytea, c_date, c_timestamp, c_int_array, c_text_array
) VALUES (
    -32768, -2147483648, -9223372036854775808, 'Infinity', 'NaN',
    '-0.000000000000000000000000000001',
    -- CJK, emoji (outside the BMP), RTL, and a combining sequence.
    U&'\4E2D\6587 ' || '👩‍👩‍👧‍👦' || ' ' || U&'\05D0\05D1\05D2' || ' e' || U&'\0301',
    -- Every one of the 256 byte values, 0x00 included.
    (SELECT decode(string_agg(lpad(to_hex(g), 2, '0'), '' ORDER BY g), 'hex')
       FROM generate_series(0, 255) AS g),
    '0001-01-01', '9999-12-31 23:59:59.999999',
    ARRAY[NULL, NULL]::integer[], ARRAY[]::text[]
);

-- Row 4: a one-megabyte string and JSON nested 50 deep.
INSERT INTO all_types (c_text, c_jsonb) VALUES (
    repeat('x', 1048576),
    (SELECT repeat('{"n":', 50) || '1' || repeat('}', 50))::jsonb
);

-- Timestamps around a DST transition, in a zone that has one.
DROP TABLE IF EXISTS dst_samples;
CREATE TABLE dst_samples (
    id    integer PRIMARY KEY,
    label text NOT NULL,
    at    timestamptz NOT NULL
);
INSERT INTO dst_samples VALUES
    (1, 'before spring forward', '2024-03-10 01:59:59.999999-05'),
    (2, 'after spring forward',  '2024-03-10 03:00:00-04'),
    (3, 'first 01:30 in fall',   '2024-11-03 01:30:00-04'),
    (4, 'second 01:30 in fall',  '2024-11-03 01:30:00-05');

-- Key shapes the grid must handle (SPEC §12.6).
DROP TABLE IF EXISTS composite_pk;
CREATE TABLE composite_pk (
    org_id  integer NOT NULL,
    user_id integer NOT NULL,
    role    text NOT NULL DEFAULT 'member',
    PRIMARY KEY (org_id, user_id)
);
INSERT INTO composite_pk VALUES (1, 1, 'owner'), (1, 2, 'member'), (2, 1, 'admin');

DROP TABLE IF EXISTS uuid_pk;
CREATE TABLE uuid_pk (
    id    uuid PRIMARY KEY,
    label text
);
INSERT INTO uuid_pk VALUES
    ('11111111-1111-1111-1111-111111111111', 'one'),
    ('22222222-2222-2222-2222-222222222222', 'two');

DROP TABLE IF EXISTS no_pk;
CREATE TABLE no_pk (a integer, b text);
INSERT INTO no_pk VALUES (1, 'x'), (1, 'x');

DROP TABLE IF EXISTS unique_not_null;
CREATE TABLE unique_not_null (code text NOT NULL UNIQUE, payload text);
INSERT INTO unique_not_null VALUES ('a', '1'), ('b', '2');

-- Relationships and derived relations.
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS customers;
CREATE TABLE customers (
    id   integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    tier mood NOT NULL DEFAULT 'ok'
);
CREATE TABLE orders (
    id          integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_id integer NOT NULL REFERENCES customers (id) ON DELETE CASCADE ON UPDATE RESTRICT,
    total       numeric(12, 2) NOT NULL DEFAULT 0,
    placed_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX orders_customer_idx ON orders (customer_id);
CREATE UNIQUE INDEX orders_unique_customer_total ON orders (customer_id, total);
INSERT INTO customers (name, tier) VALUES ('Ada', 'happy'), ('Grace', 'ok');
INSERT INTO orders (customer_id, total) VALUES (1, 10.50), (1, 20.00), (2, 5.25);

DROP VIEW IF EXISTS customer_totals;
CREATE VIEW customer_totals AS
SELECT c.id, c.name, sum(o.total) AS total
FROM customers c LEFT JOIN orders o ON o.customer_id = c.id
GROUP BY c.id, c.name;

DROP MATERIALIZED VIEW IF EXISTS customer_totals_mv;
CREATE MATERIALIZED VIEW customer_totals_mv AS SELECT * FROM customer_totals;

CREATE OR REPLACE FUNCTION add_numbers(a integer, b integer) RETURNS integer
LANGUAGE sql IMMUTABLE AS $$ SELECT a + b $$;

CREATE OR REPLACE PROCEDURE touch_customer(cid integer)
LANGUAGE plpgsql AS $$
BEGIN
    UPDATE customers SET name = name WHERE id = cid;
END;
$$;
