-- One million rows for the data-grid performance criteria (SPEC §12.6), generated by a
-- recursive CTE in one statement.
DROP TABLE IF EXISTS big_table;
CREATE TABLE big_table (
    id       INTEGER PRIMARY KEY,
    name     TEXT NOT NULL,
    amount   NUMERIC(12, 2) NOT NULL,
    flag     BOOLEAN NOT NULL,
    created  DATETIME NOT NULL
);
INSERT INTO big_table (id, name, amount, flag, created)
WITH RECURSIVE series(g) AS (SELECT 1 UNION ALL SELECT g + 1 FROM series WHERE g < 1000000)
SELECT g,
       'row ' || g,
       (g % 100000) / 100.0,
       g % 2 = 0,
       datetime('2020-01-01 00:00:00', '+' || g || ' seconds')
FROM series;
ANALYZE big_table;
