import DBCore
import XCTest

@testable import DBSQL

/// The diff that drives the table designer (SPEC §15b.2).
///
/// Every test here asserts the exact statement text. The generator's whole job is to be
/// predictable, and a test that only checks "some statement was produced" would pass on
/// SQL no server accepts.
final class DDLGeneratorTests: XCTestCase {
    let pgTable = TableRef(database: "d", schema: "public", name: "customers")
    let myTable = TableRef(database: "d", schema: "d", name: "customers")

    func pg() -> DDLGenerator { DDLGenerator(dialect: .postgresql) }
    func my() -> DDLGenerator { DDLGenerator(dialect: .mysql) }

    /// A definition with one integer id and one text name.
    func base(
        _ table: TableRef, idColumn: ColumnDefinition, nameColumn: ColumnDefinition
    )
        -> TableDefinition
    {
        TableDefinition(ref: table, columns: [idColumn, nameColumn], primaryKey: ["id"])
    }

    // MARK: - Create

    func testCreateTablePostgres() {
        let definition = TableDefinition(
            ref: pgTable,
            columns: [
                ColumnDefinition(name: "id", type: "integer", isNullable: false, isAutoIncrement: true),
                ColumnDefinition(name: "name", type: "text", isNullable: false),
                ColumnDefinition(name: "tier", type: "text", defaultExpression: "'ok'"),
            ],
            primaryKey: ["id"]
        )
        let statements = pg().create(definition)
        XCTAssertEqual(statements.count, 1)
        XCTAssertEqual(statements[0].kind, .createTable)
        XCTAssertEqual(
            statements[0].sql,
            """
            CREATE TABLE "public"."customers" (
                "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                "name" text NOT NULL,
                "tier" text DEFAULT 'ok',
                PRIMARY KEY ("id")
            )
            """)
    }

    func testCreateTableMySQLCarriesItsOptionsAndComment() {
        let definition = TableDefinition(
            ref: myTable,
            comment: "people who buy things",
            columns: [
                ColumnDefinition(name: "id", type: "int", isNullable: false, isAutoIncrement: true)
            ],
            primaryKey: ["id"],
            options: TableOptions(engine: "InnoDB", characterSet: "utf8mb4", collation: "utf8mb4_0900_ai_ci")
        )
        let sql = my().create(definition)[0].sql
        XCTAssertTrue(sql.contains("`id` int NOT NULL AUTO_INCREMENT"), sql)
        XCTAssertTrue(sql.contains("PRIMARY KEY (`id`)"), sql)
        XCTAssertTrue(sql.contains("ENGINE = InnoDB"), sql)
        XCTAssertTrue(sql.contains("DEFAULT CHARSET = utf8mb4"), sql)
        XCTAssertTrue(sql.contains("COMMENT = 'people who buy things'"), sql)
    }

    func testCreateEmitsIndexesAndCommentsAfterTheTable() {
        let definition = TableDefinition(
            ref: pgTable,
            comment: "a table",
            columns: [ColumnDefinition(name: "name", type: "text", comment: "their name")],
            indexes: [IndexDefinition(name: "customers_name_idx", columns: [IndexColumn(name: "name")])]
        )
        let kinds = pg().create(definition).map(\.kind)
        XCTAssertEqual(kinds, [.createTable, .createIndex, .comment, .comment])
    }

    // MARK: - Columns

    func testAddingAColumn() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        var edited = base(pgTable, idColumn: id, nameColumn: name)
        edited.columns.append(ColumnDefinition(name: "email", type: "text", isNullable: false))

        let statements = pg().alter(from: base(pgTable, idColumn: id, nameColumn: name), to: edited)
        XCTAssertEqual(statements.count, 1)
        XCTAssertEqual(statements[0].kind, .addColumn)
        XCTAssertEqual(
            statements[0].sql,
            #"ALTER TABLE "public"."customers" ADD COLUMN "email" text NOT NULL"#
        )
        XCTAssertFalse(statements[0].isDestructive)
    }

    func testDroppingAColumnIsMarkedDestructive() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        var edited = base(pgTable, idColumn: id, nameColumn: name)
        edited.columns.removeAll { $0.id == name.id }

        let statements = pg().alter(from: base(pgTable, idColumn: id, nameColumn: name), to: edited)
        XCTAssertEqual(statements.count, 1)
        XCTAssertEqual(statements[0].kind, .dropColumn)
        XCTAssertTrue(statements[0].isDestructive, "dropping a column loses its data")
        XCTAssertEqual(
            statements[0].sql,
            #"ALTER TABLE "public"."customers" DROP COLUMN "name""#
        )
    }

    /// The point of the stable id: keeping it means renamed, losing it means replaced.
    func testRenamingAColumnIsARenameNotADropAndAdd() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        var edited = base(pgTable, idColumn: id, nameColumn: name)
        edited.columns[1].name = "full_name"

        let statements = pg().alter(from: base(pgTable, idColumn: id, nameColumn: name), to: edited)
        XCTAssertEqual(statements.map(\.kind), [.renameColumn])
        XCTAssertEqual(
            statements[0].sql,
            #"ALTER TABLE "public"."customers" RENAME COLUMN "name" TO "full_name""#
        )
    }

    func testPostgresChangesOneFacetOfAColumnAtATime() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        var edited = base(pgTable, idColumn: id, nameColumn: name)
        edited.columns[1].type = "varchar(120)"
        edited.columns[1].isNullable = false
        edited.columns[1].defaultExpression = "''"

        let statements = pg().alter(from: base(pgTable, idColumn: id, nameColumn: name), to: edited)
        XCTAssertEqual(
            statements.map(\.sql),
            [
                #"ALTER TABLE "public"."customers" ALTER COLUMN "name" TYPE varchar(120) USING "name"::varchar(120)"#,
                #"ALTER TABLE "public"."customers" ALTER COLUMN "name" SET NOT NULL"#,
                #"ALTER TABLE "public"."customers" ALTER COLUMN "name" SET DEFAULT ''"#,
            ])
        XCTAssertTrue(statements[0].isDestructive, "a type change can lose data")
    }

    func testMySQLRestatesTheWholeColumn() {
        let id = ColumnDefinition(name: "id", type: "int", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        var edited = base(myTable, idColumn: id, nameColumn: name)
        edited.columns[1].type = "varchar(120)"
        edited.columns[1].isNullable = false

        let statements = my().alter(from: base(myTable, idColumn: id, nameColumn: name), to: edited)
        XCTAssertEqual(
            statements.map(\.sql),
            [
                "ALTER TABLE `d`.`customers` MODIFY COLUMN `name` varchar(120) NOT NULL"
            ])
    }

    func testDroppingADefaultRatherThanSettingOne() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text", defaultExpression: "'x'")
        var edited = base(pgTable, idColumn: id, nameColumn: name)
        edited.columns[1].defaultExpression = nil

        let statements = pg().alter(from: base(pgTable, idColumn: id, nameColumn: name), to: edited)
        XCTAssertEqual(
            statements.map(\.sql),
            [#"ALTER TABLE "public"."customers" ALTER COLUMN "name" DROP DEFAULT"#]
        )
    }

    func testAGeneratedColumnTakesItsExpressionAndStorage() {
        let generator = DDLGenerator(dialect: .mysql)
        let column = ColumnDefinition(
            name: "total_with_tax",
            type: "decimal(12,2)",
            generatedExpression: "`total` * 1.1",
            isGeneratedStored: false
        )
        XCTAssertEqual(
            generator.columnClause(column),
            "`total_with_tax` decimal(12,2) GENERATED ALWAYS AS (`total` * 1.1) VIRTUAL"
        )
    }

    // MARK: - Primary key

    func testSettingAPrimaryKeyOnATableThatHadNone() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        var current = base(pgTable, idColumn: id, nameColumn: name)
        current.primaryKey = []
        var edited = current
        edited.primaryKey = ["id"]

        let statements = pg().alter(from: current, to: edited)
        XCTAssertEqual(statements.map(\.kind), [.addPrimaryKey])
        XCTAssertEqual(
            statements[0].sql,
            #"ALTER TABLE "public"."customers" ADD PRIMARY KEY ("id")"#
        )
    }

    /// One edit, not two: the old key comes off and the new one goes on in the same run.
    func testChangingAPrimaryKeyDropsThenAdds() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text", isNullable: false)
        let current = base(pgTable, idColumn: id, nameColumn: name)
        var edited = current
        edited.primaryKey = ["id", "name"]

        let statements = pg().alter(from: current, to: edited)
        XCTAssertEqual(statements.map(\.kind), [.dropPrimaryKey, .addPrimaryKey])
        XCTAssertEqual(
            statements[0].sql,
            #"ALTER TABLE "public"."customers" DROP CONSTRAINT "customers_pkey""#
        )
        XCTAssertEqual(
            statements[1].sql,
            #"ALTER TABLE "public"."customers" ADD PRIMARY KEY ("id", "name")"#
        )
    }

    func testMySQLDropsThePrimaryKeyWithItsOwnSyntax() {
        let id = ColumnDefinition(name: "id", type: "int", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        let current = base(myTable, idColumn: id, nameColumn: name)
        var edited = current
        edited.primaryKey = []

        let statements = my().alter(from: current, to: edited)
        XCTAssertEqual(statements.map(\.sql), ["ALTER TABLE `d`.`customers` DROP PRIMARY KEY"])
    }

    // MARK: - Indexes

    func testCreatingABtreeIndex() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        let current = base(pgTable, idColumn: id, nameColumn: name)
        var edited = current
        edited.indexes = [
            IndexDefinition(
                name: "customers_name_idx",
                columns: [IndexColumn(name: "name")],
                method: "btree"
            )
        ]

        let statements = pg().alter(from: current, to: edited)
        XCTAssertEqual(statements.map(\.kind), [.createIndex])
        XCTAssertEqual(
            statements[0].sql,
            #"CREATE INDEX "customers_name_idx" ON "public"."customers" USING btree ("name")"#
        )
    }

    func testAUniquePartialIndexWithASortDirection() {
        let index = IndexDefinition(
            name: "active_email_idx",
            columns: [IndexColumn(name: "email", isDescending: true)],
            isUnique: true,
            method: "btree",
            predicate: "deleted_at IS NULL"
        )
        XCTAssertEqual(
            pg().createIndexSQL(index, on: pgTable),
            #"CREATE UNIQUE INDEX "active_email_idx" ON "public"."customers" USING btree ("email" DESC) WHERE deleted_at IS NULL"#
        )
    }

    /// MySQL spells FULLTEXT as a kind of index, not as a method.
    func testMySQLFulltextIndex() {
        let index = IndexDefinition(
            name: "body_ft", columns: [IndexColumn(name: "body")], method: "fulltext"
        )
        XCTAssertEqual(
            my().createIndexSQL(index, on: myTable),
            "CREATE FULLTEXT INDEX `body_ft` ON `d`.`customers` (`body`)"
        )
    }

    func testMySQLIndexPrefixLength() {
        let index = IndexDefinition(
            name: "name_idx", columns: [IndexColumn(name: "name", prefixLength: 20)], method: "btree"
        )
        XCTAssertEqual(
            my().createIndexSQL(index, on: myTable),
            "CREATE INDEX `name_idx` ON `d`.`customers` (`name`(20)) USING BTREE"
        )
    }

    func testChangingAnIndexRebuildsIt() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        var current = base(pgTable, idColumn: id, nameColumn: name)
        let index = IndexDefinition(name: "n_idx", columns: [IndexColumn(name: "name")])
        current.indexes = [index]
        var edited = current
        edited.indexes[0].isUnique = true

        let statements = pg().alter(from: current, to: edited)
        XCTAssertEqual(statements.map(\.kind), [.dropIndex, .createIndex])
        XCTAssertFalse(statements[0].isDestructive, "a rebuilt index is not lost data")
    }

    /// A renamed index keeps its contents, so it is renamed rather than rebuilt.
    func testRenamingAnIndexDoesNotRebuildIt() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        var current = base(pgTable, idColumn: id, nameColumn: name)
        current.indexes = [IndexDefinition(name: "old_idx", columns: [IndexColumn(name: "name")])]
        var edited = current
        edited.indexes[0].name = "new_idx"

        let statements = pg().alter(from: current, to: edited)
        XCTAssertEqual(statements.map(\.kind), [.renameIndex])
        XCTAssertEqual(
            statements[0].sql,
            #"ALTER INDEX "public"."old_idx" RENAME TO "new_idx""#
        )
    }

    func testDroppingAnIndexIsSchemaQualifiedOnPostgresAndTableScopedOnMySQL() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")

        var pgCurrent = base(pgTable, idColumn: id, nameColumn: name)
        pgCurrent.indexes = [IndexDefinition(name: "n_idx", columns: [IndexColumn(name: "name")])]
        var pgEdited = pgCurrent
        pgEdited.indexes = []
        XCTAssertEqual(
            pg().alter(from: pgCurrent, to: pgEdited).map(\.sql),
            [#"DROP INDEX "public"."n_idx""#]
        )

        var myCurrent = base(myTable, idColumn: id, nameColumn: name)
        myCurrent.indexes = [IndexDefinition(name: "n_idx", columns: [IndexColumn(name: "name")])]
        var myEdited = myCurrent
        myEdited.indexes = []
        XCTAssertEqual(
            my().alter(from: myCurrent, to: myEdited).map(\.sql),
            ["DROP INDEX `n_idx` ON `d`.`customers`"]
        )
    }

    // MARK: - Foreign keys and checks

    func testAddingACompositeForeignKeyWithActions() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        let current = base(pgTable, idColumn: id, nameColumn: name)
        var edited = current
        edited.foreignKeys = [
            ForeignKeyDefinition(
                name: "customers_org_fk",
                columns: ["org_id", "user_id"],
                referencedTable: TableRef(database: "d", schema: "public", name: "composite_pk"),
                referencedColumns: ["org_id", "user_id"],
                onUpdate: .restrict,
                onDelete: .cascade
            )
        ]

        let statements = pg().alter(from: current, to: edited)
        XCTAssertEqual(statements.map(\.kind), [.addForeignKey])
        XCTAssertEqual(
            statements[0].sql,
            """
            ALTER TABLE "public"."customers" ADD CONSTRAINT "customers_org_fk" \
            FOREIGN KEY ("org_id", "user_id") REFERENCES "public"."composite_pk" ("org_id", "user_id") \
            ON UPDATE RESTRICT ON DELETE CASCADE
            """)
    }

    func testMySQLDropsAForeignKeyWithItsOwnKeyword() {
        let id = ColumnDefinition(name: "id", type: "int", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        var current = base(myTable, idColumn: id, nameColumn: name)
        current.foreignKeys = [
            ForeignKeyDefinition(
                name: "fk", columns: ["id"],
                referencedTable: myTable, referencedColumns: ["id"]
            )
        ]
        var edited = current
        edited.foreignKeys = []

        XCTAssertEqual(
            my().alter(from: current, to: edited).map(\.sql),
            ["ALTER TABLE `d`.`customers` DROP FOREIGN KEY `fk`"]
        )
    }

    func testCheckConstraintRoundTripsItsExpressionVerbatim() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        let current = base(pgTable, idColumn: id, nameColumn: name)
        var edited = current
        edited.checks = [CheckDefinition(name: "positive_id", expression: "id > 0")]

        let statements = pg().alter(from: current, to: edited)
        XCTAssertEqual(
            statements.map(\.sql),
            [#"ALTER TABLE "public"."customers" ADD CONSTRAINT "positive_id" CHECK (id > 0)"#]
        )
    }

    // MARK: - Names from a catalogue are never trusted as SQL

    /// A character set, collation, engine, index method or operator class read from a
    /// hostile server must not be able to end the clause it sits in.
    func testCatalogueNamesThatAreNotBareWordsAreQuoted() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        var name = ColumnDefinition(name: "name", type: "varchar(20)")
        name.characterSet = "utf8mb4; DROP TABLE x; --"
        name.collation = "utf8mb4_bin`; DROP TABLE y; --"
        var definition = base(myTable, idColumn: id, nameColumn: name)
        definition.options = TableOptions(
            engine: "InnoDB; DROP TABLE z", characterSet: "utf8mb4\"", collation: "utf8mb4_0900_ai_ci")
        let create = my().create(definition).map(\.sql)
        XCTAssertEqual(
            create.first,
            "CREATE TABLE `d`.`customers` (\n    `id` integer NOT NULL,\n"
                + "    `name` varchar(20) CHARACTER SET `utf8mb4; DROP TABLE x; --` "
                + "COLLATE `utf8mb4_bin``; DROP TABLE y; --`,\n    PRIMARY KEY (`id`)\n) "
                + "ENGINE = `InnoDB; DROP TABLE z` DEFAULT CHARSET = `utf8mb4\"` COLLATE = utf8mb4_0900_ai_ci"
        )

        var current = base(pgTable, idColumn: id, nameColumn: ColumnDefinition(name: "name", type: "text"))
        var edited = current
        edited.indexes = [
            IndexDefinition(
                name: "n_idx", columns: [IndexColumn(name: "name", operatorClass: "text_pattern_ops; DROP TABLE q")],
                method: "btree); DROP TABLE p; --")
        ]
        XCTAssertEqual(
            pg().alter(from: current, to: edited).map(\.sql),
            [
                #"CREATE INDEX "n_idx" ON "public"."customers" USING "btree); DROP TABLE p; --" "#
                    + #"("name" "text_pattern_ops; DROP TABLE q")"#
            ]
        )
        // A plain name stays a plain word, as every server expects it.
        current.options = TableOptions(engine: nil)
        edited = current
        edited.indexes = [IndexDefinition(name: "n_idx", columns: [IndexColumn(name: "name")], method: "gin")]
        XCTAssertEqual(
            pg().alter(from: current, to: edited).map(\.sql),
            [#"CREATE INDEX "n_idx" ON "public"."customers" USING gin ("name")"#]
        )
    }

    /// A type goes into a statement only as `ColumnTypeSpec` renders it: members quoted,
    /// anything that is not type spelling dropped.
    func testTypesAreRenderedThroughTheSpec() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        let current = base(pgTable, idColumn: id, nameColumn: name)
        var edited = current
        edited.columns[1].type = "varchar(50); DROP TABLE customers; --"
        XCTAssertEqual(
            pg().alter(from: current, to: edited).map(\.sql),
            [
                #"ALTER TABLE "public"."customers" ALTER COLUMN "name" TYPE varchar(50)  DROP TABLE customers  "#
                    + #"USING "name"::varchar(50)  DROP TABLE customers "#
            ]
        )
        var mysqlEdited = base(myTable, idColumn: id, nameColumn: name)
        mysqlEdited.columns[1].type = "enum('a','b'); DROP TABLE t"
        let clause = my().columnClause(mysqlEdited.columns[1])
        XCTAssertEqual(clause, "`name` enum('a','b')  DROP TABLE t")
    }

    // MARK: - Ordering

    /// Constraints come off before the columns they sit on, and go back on afterwards.
    /// Any other order and the server refuses the change for its own reasons.
    func testStatementOrderDropsDependantsFirstAndRebuildsThemLast() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        var current = base(pgTable, idColumn: id, nameColumn: name)
        current.indexes = [IndexDefinition(name: "n_idx", columns: [IndexColumn(name: "name")])]
        current.checks = [CheckDefinition(name: "c", expression: "id > 0")]
        current.foreignKeys = [
            ForeignKeyDefinition(
                name: "fk", columns: ["id"], referencedTable: pgTable, referencedColumns: ["id"]
            )
        ]

        var edited = current
        edited.columns[1].type = "varchar(50)"
        edited.indexes[0].isUnique = true
        edited.checks[0].expression = "id > 1"
        edited.foreignKeys[0].onDelete = .cascade
        edited.primaryKey = ["id", "name"]

        let kinds = pg().alter(from: current, to: edited).map(\.kind)
        XCTAssertEqual(
            kinds,
            [
                .dropForeignKey, .dropCheck, .dropIndex, .dropPrimaryKey,
                .alterColumn,
                .addPrimaryKey, .createIndex, .addCheck, .addForeignKey,
            ])
    }

    func testNoChangesProduceNoStatements() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        let definition = base(pgTable, idColumn: id, nameColumn: name)
        XCTAssertTrue(pg().alter(from: definition, to: definition).isEmpty)
        XCTAssertTrue(my().alter(from: definition, to: definition).isEmpty)
    }

    // MARK: - Column order

    func testMovingAColumnRestatesItAfterItsNewNeighbourOnMySQL() {
        let id = ColumnDefinition(name: "id", type: "int", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        let email = ColumnDefinition(name: "email", type: "text")
        var current = base(myTable, idColumn: id, nameColumn: name)
        current.columns.append(email)

        var edited = current
        edited.columns = [id, email, name]

        let statements = my().alter(from: current, to: edited)
        XCTAssertEqual(
            statements.map(\.sql),
            [
                "ALTER TABLE `d`.`customers` MODIFY COLUMN `id` int NOT NULL FIRST",
                "ALTER TABLE `d`.`customers` MODIFY COLUMN `email` text AFTER `id`",
                "ALTER TABLE `d`.`customers` MODIFY COLUMN `name` text AFTER `email`",
            ])
    }

    /// PostgreSQL cannot move a column at all, so nothing is emitted rather than SQL the
    /// server would reject.
    func testPostgresEmitsNothingForAReorder() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        let email = ColumnDefinition(name: "email", type: "text")
        var current = base(pgTable, idColumn: id, nameColumn: name)
        current.columns.append(email)
        var edited = current
        edited.columns = [id, email, name]

        XCTAssertTrue(pg().alter(from: current, to: edited).isEmpty)
    }

    /// Adding a column changes the sequence without anything having moved.
    func testAddingAColumnIsNotAReorder() {
        let id = ColumnDefinition(name: "id", type: "int", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        let current = base(myTable, idColumn: id, nameColumn: name)
        var edited = current
        edited.columns.append(ColumnDefinition(name: "email", type: "text"))

        let kinds = my().alter(from: current, to: edited).map(\.kind)
        XCTAssertEqual(kinds, [.addColumn], "no MODIFY statements for an append")
    }

    // MARK: - Partitions

    func testAddingAPartition() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let taken = ColumnDefinition(name: "taken_at", type: "date", isNullable: false)
        var current = TableDefinition(ref: pgTable, columns: [id, taken])
        current.partitioning = PartitioningInfo(
            strategy: .range, key: "taken_at",
            partitions: [PartitionInfo(name: "m_2024", bound: "FOR VALUES FROM ('2024-01-01') TO ('2025-01-01')")]
        )
        var edited = current
        edited.partitioning = PartitioningInfo(
            strategy: .range, key: "taken_at",
            partitions: current.partitioning!.partitions + [
                PartitionInfo(name: "m_2025", bound: "FOR VALUES FROM ('2025-01-01') TO ('2026-01-01')")
            ]
        )

        let statements = pg().alter(from: current, to: edited)
        XCTAssertEqual(statements.map(\.kind), [.partition])
        XCTAssertEqual(
            statements[0].sql,
            #"CREATE TABLE "public"."m_2025" PARTITION OF "public"."customers" FOR VALUES FROM ('2025-01-01') TO ('2026-01-01')"#
        )
        XCTAssertFalse(statements[0].isDestructive)
    }

    /// PostgreSQL detaches and keeps the rows; MySQL drops them. Only one is destructive,
    /// and the preview says which.
    func testRemovingAPartitionDetachesOnPostgresAndDropsOnMySQL() {
        func definition(_ table: TableRef) -> TableDefinition {
            var value = TableDefinition(
                ref: table,
                columns: [ColumnDefinition(name: "id", type: "int", isNullable: false)]
            )
            value.partitioning = PartitioningInfo(
                strategy: .range, key: "id",
                partitions: [PartitionInfo(name: "p_old", bound: "VALUES LESS THAN (10)")]
            )
            return value
        }

        var pgCurrent = definition(pgTable)
        var pgEdited = pgCurrent
        pgEdited.partitioning = PartitioningInfo(strategy: .range, key: "id", partitions: [])
        let pgStatements = pg().alter(from: pgCurrent, to: pgEdited)
        XCTAssertEqual(
            pgStatements.map(\.sql),
            [#"ALTER TABLE "public"."customers" DETACH PARTITION "public"."p_old""#]
        )
        XCTAssertFalse(pgStatements[0].isDestructive, "detaching keeps the rows")
        pgCurrent = pgEdited

        var myCurrent = definition(myTable)
        var myEdited = myCurrent
        myEdited.partitioning = PartitioningInfo(strategy: .range, key: "id", partitions: [])
        let myStatements = my().alter(from: myCurrent, to: myEdited)
        XCTAssertEqual(
            myStatements.map(\.sql),
            ["ALTER TABLE `d`.`customers` DROP PARTITION `p_old`"]
        )
        XCTAssertTrue(myStatements[0].isDestructive, "MySQL discards the rows")
        myCurrent = myEdited
    }

    func testAnUnpartitionedTableProducesNoPartitionStatements() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        let definition = base(pgTable, idColumn: id, nameColumn: name)
        XCTAssertTrue(pg().alter(from: definition, to: definition).isEmpty)
    }

    // MARK: - Triggers

    func testCreatingATriggerOnEachDialect() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        var current = base(pgTable, idColumn: id, nameColumn: name)
        var edited = current
        edited.triggers = [
            TriggerInfo(
                name: "bump",
                timing: .before,
                events: [.update],
                isRowLevel: true,
                condition: "OLD.id IS NOT NULL",
                functionCall: "\"public\".\"bump_touched\"()"
            )
        ]

        let pgStatements = pg().alter(from: current, to: edited)
        XCTAssertEqual(pgStatements.map(\.kind), [.createTrigger])
        XCTAssertEqual(
            pgStatements[0].sql,
            #"CREATE TRIGGER "bump" BEFORE UPDATE ON "public"."customers" FOR EACH ROW WHEN (OLD.id IS NOT NULL) EXECUTE FUNCTION "public"."bump_touched"()"#
        )

        current = base(myTable, idColumn: id, nameColumn: name)
        edited = current
        edited.triggers = [
            TriggerInfo(
                name: "bump", timing: .before, events: [.update],
                body: "SET NEW.touched = OLD.touched + 1"
            )
        ]
        let myStatements = my().alter(from: current, to: edited)
        XCTAssertEqual(
            myStatements[0].sql,
            """
            CREATE TRIGGER `bump` BEFORE UPDATE ON `d`.`customers` FOR EACH ROW
            SET NEW.touched = OLD.touched + 1
            """)
    }

    func testDroppingATriggerIsDestructiveAndScopedPerDialect() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        var pgCurrent = base(pgTable, idColumn: id, nameColumn: name)
        pgCurrent.triggers = [TriggerInfo(name: "bump", timing: .before, events: [.update])]
        var pgEdited = pgCurrent
        pgEdited.triggers = []

        let pgStatements = pg().alter(from: pgCurrent, to: pgEdited)
        XCTAssertEqual(
            pgStatements.map(\.sql),
            [#"DROP TRIGGER "bump" ON "public"."customers""#]
        )
        XCTAssertTrue(pgStatements[0].isDestructive)

        var myCurrent = base(myTable, idColumn: id, nameColumn: name)
        myCurrent.triggers = [TriggerInfo(name: "bump", timing: .before, events: [.update])]
        var myEdited = myCurrent
        myEdited.triggers = []
        XCTAssertEqual(
            my().alter(from: myCurrent, to: myEdited).map(\.sql),
            ["DROP TRIGGER `d`.`bump`"]
        )
    }

    // MARK: - Comments, rename, drop

    func testPostgresCommentsAreTheirOwnStatements() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        let current = base(pgTable, idColumn: id, nameColumn: name)
        var edited = current
        edited.comment = "who buys"
        edited.columns[1].comment = "their name"

        let statements = pg().alter(from: current, to: edited)
        XCTAssertEqual(
            statements.map(\.sql),
            [
                #"COMMENT ON TABLE "public"."customers" IS 'who buys'"#,
                #"COMMENT ON COLUMN "public"."customers"."name" IS 'their name'"#,
            ])
    }

    func testRenamingATable() {
        let id = ColumnDefinition(name: "id", type: "integer", isNullable: false)
        let name = ColumnDefinition(name: "name", type: "text")
        let current = base(pgTable, idColumn: id, nameColumn: name)
        var edited = current
        edited.ref = TableRef(database: "d", schema: "public", name: "clients")

        let statements = pg().alter(from: current, to: edited)
        XCTAssertEqual(statements.map(\.kind), [.renameTable])
        XCTAssertEqual(
            statements[0].sql,
            #"ALTER TABLE "public"."customers" RENAME TO "clients""#
        )
    }

    func testDropTableIsAlwaysDestructive() {
        let statement = pg().drop(pgTable)
        XCTAssertTrue(statement.isDestructive)
        XCTAssertEqual(statement.sql, #"DROP TABLE "public"."customers""#)
    }

    // MARK: - Reading a definition out of introspection

    /// The index that implements the primary key is not shown beside the others, or the
    /// user would be able to edit the same thing in two places.
    func testDefinitionFromIntrospectionDropsThePrimaryKeyIndex() {
        let definition = TableDefinition(
            table: pgTable,
            info: TableInfo(ref: pgTable, kind: .table, comment: "c"),
            columns: [
                ColumnInfo(
                    ordinal: 1, name: "id", nativeType: "integer", kind: .int, isNullable: false,
                    isPrimaryKey: true
                )
            ],
            primaryKey: ["id"],
            indexes: [
                IndexInfo(name: "customers_pkey", columns: ["id"], isUnique: true, isPrimary: true),
                IndexInfo(name: "customers_name_idx", columns: ["name"], isUnique: false, method: "btree"),
            ],
            foreignKeys: []
        )
        XCTAssertEqual(definition.primaryKey, ["id"])
        XCTAssertEqual(definition.indexes.map(\.name), ["customers_name_idx"])
        XCTAssertEqual(definition.comment, "c")
    }
}
